# Generated by Django 4.2.5 on 2023-09-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedcheckapp', '0005_remove_result_user_profile_result_user_id'),
        ('myauth', '0004_remove_profile_results'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
